piga/piga/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('work.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

piga/work/urls.py
# project/urls.py

from django.urls import re_path, path
from . import views

app_name = 'project'
urlpatterns = [

    # 登陆、注册 以及 信息、密码修改
    path('', views.index, name='index'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$', views.pwd_change, name='pwd_change'),
    re_path(r'^logout/$', views.logout, name='logout'),

]

piga/templates/login.html
<!--templates/project/login.html-->

{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>登陆</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<style type="text/css">
body{
    background: url("../img/1.jpg");
    animation-name:myfirst;
    animation-duration:12s;
    /*变换时间*/
    animation-delay:2s;
    /*动画开始时间*/
    animation-iteration-count:infinite;
    /*下一周期循环播放*/
    animation-play-state:running;
    /*动画开始运行*/
}
@keyframes myfirst
{
    0%   {background:url("{% static '/img/th1.jpg' %}");}
    50%  {background:url("{% static '/img/th2.jpg' %}");}
    100% {background:url("{% static '/img/th1.jpg' %}");}
}
.form{background: rgba(255,255,255,0.2);width:400px;margin:120px auto;}
/*阴影*/
.fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
input[type="text"],input[type="password"]{padding-left:26px;}

</style>

<body>
{% block content %}
<div class="container">
    <div class="form row">
        <div class="form-horizontal col-md-offset-3" id="login_form">
            <h3 class="form-title">登陆</h3>
            <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
            	{% csrf_token %}
            <div class="col-md-9">
                <div class="form-group">
                    <i class="fa fa-user fa-lg"></i>
                    <input class="form-control required" type="text" placeholder="Username" id="username" name="username"/>
                </div>
                <div class="form-group">
                    <i class="fa fa-lock fa-lg"></i>
                    <input class="form-control required" type="password" placeholder="Password" id="password" name="password"/>
                </div>
                <div class="form-group">
                    <a href="{% url 'project:register' %}">注册</a>
                </div>
                <div class="form-group col-md-offset-9">
                    <button type="submit" class="btn btn-success pull-right" name="submit">登录</button>
                </div>
            </div>
        	</form>
        </div>
    </div>
</div>
{% endblock %}
</body>

</html>

piga/templates/profile.html
<!-- templates/project/profile.html-->
{% extends "project/base.html" %}
{% load static %}
{% block content %}

<body class="gray-bg">
    <div class="wrapper wrapper-content">
        <div class="row animated fadeInRight">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>个人资料</h5>
                    </div>
                    <div>
                        <div class="ibox-content no-padding border-left-right" align="center">
                            <a class="" href="#" title="">
                                <img alt="image" class="img-responsive" src="{% static '/img/p_big2.jpg' %}" >
                            </a>
                        </div>
                        <div class="ibox-content profile-content">
                            <h4><strong>姓名：{{ user.role.student.name }}{{ user.role.teacher.name }}</strong></h4>
                            <h4>用户名: {{ user.username }}</h4>
                            <h4>Email: {{ user.email }} </h4>

                            <p><i class="fa fa-map-marker"></i> 河北省xxxxxxxxxxxxx</p>
                            <h5>自我描述</h5>
                            <p>
                                会点前端技术，div+css啊，jQuery之类的，不是很精；热爱生活，热爱互联网，热爱新技术；有一个小的团队，在不断的寻求新的突破。
                            </p>
                            <p>
                                <ul>
                                    {% if request.user.role.role == 1 %}
                                        {% if request.user.role.teacher.gender %}
                                            <li>性别: 女 </li>
                                        {% else %}
                                            <li>性别: 男 </li>
                                        {% endif %}
                                    {% else %}
                                        {% if request.user.role.student.gender %}
                                            <li>性别: 女 </li>
                                        {% else %}
                                            <li>性别: 男 </li>
                                        {% endif %}
                                    {% endif %}

                                    {% if request.user.role.role == 1 %}
                                        <li>用户类型：教师 </li>
                                    {% else %}
                                        <li>用户类型：学生 </li>
                                    {% endif %}
                                    {% if user.role.role == 1 %}
                                    <li>职称: {{ user.role.teacher.ranks }} </li>
                                    {% else %}
                                    <li>班级: {{ user.role.student.classes }} </li>
                                    {% endif %}
                                </ul>
                            </p>
                            <div class="row m-t-lg">
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                </div>
                            </div>
                            <div class="user-button">
                                <div class="row">
                                    <div class="col-sm-6">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'project:profile_update' user.id %}">
                                            <button type="button" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i> 编辑信息</button>
                                        </a>
                                        {% endif %}
                                    </div>
                                    <div class="col-sm-6">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'project:pwd_change' user.id %}">
                                            <button type="button" class="btn btn-default btn-sm btn-block"><span class="glyphicon glyphicon-wrench"> </span> 修改密码</button>
                                        </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>

</body>


{% endblock %}

piga/templates/registration.html
<!--templates/project/registration.html-->

{% extends "project/base.html" %}
{% block content %}


<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

            </div>
            <h3>欢迎注册 </h3>
            <form class="m-t" method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">注 册</button>

            </form>

        </div>
    </div>

</body>

</html>

{% endblock %}