JXProject/JXProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
import xadmin
from apps.article.views import SearchView

urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),
    path('account/', include('apps.account.urls', namespace='account')),
    path('note/', include(('apps.notes.urls', 'note'), namespace='note')),
    path('article/', include(('apps.article.urls', 'article'), namespace='article')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('test/', TemplateView.as_view(template_name="test/extest.html"), name='test'),
    path('calen/', TemplateView.as_view(template_name="calen.html"), name='calen'),

]

JXProject/apps/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    # path("login/", views.user_login, name='user_login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),

    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name="account/password_change_form.html",
        success_url="/account/password-change-done/"), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeView.as_view(
        template_name="account/password_change_done.html"), name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name="account/password_rest_form.html",
        email_template_name="account/password_reset_email.html",
        success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html",
        success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'), name='password_reset_complete'),

    path('my-information/', views.myself, name="my_information"),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),



]

JXProject/apps/article/urls.py
from django.urls import path, re_path
from . import views, list_views

app_name = "article"

urlpatterns = [
    path('article-column/', views.article_column, name="article_column"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),
    path('del-column/', views.del_article_column, name="del_article_column"),
    path('article-post/', views.article_post, name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    #接收id,slug参数
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del-article/', views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),

    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),
    path('list-article-titles/<username>/', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),

    path('article-tag/', views.article_tag, name="article_tag"),
    path('del-article-tag/', views.del_article_tag, name="del_article_tag"),
]

JXProject/apps/course/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import AboutView, CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView, \
    CreateLessonView, ListLessonsView, DetailLessonView, StudentListLessonView

app_name = "course"

urlpatterns = [
    #path('about/', TemplateView.as_view(template_name="course/about.html")),
    path('about/', AboutView.as_view(), name="about"),
    path('course-list/', CourseListView.as_view(), name="course_list"),
    path('manage-course/', ManageCourseListView.as_view(), name="manage_course"),
    path('create-course/', CreateCourseView.as_view(), name="create_course"),
    path('delete-course/<int:pk>/', DeleteCourseView.as_view(),name="delete_course"),
    path('create-lesson/', CreateLessonView.as_view(), name="create_lesson"),
    path('list-lessons/<int:course_id>/', ListLessonsView.as_view(), name="list_lessons"),
    path('detail-lesson/<int:lesson_id>/', DetailLessonView.as_view(), name="detail_lesson"),
    path('lessons-list/<int:course_id>/', StudentListLessonView.as_view(), name="lessons_list"),
    ]

JXProject/apps/notes/urls.py
from django.urls import path
from . import views

app_name = "note"

urlpatterns = [
    path("", views.note_title, name='note_title'),
    #path('<int:article_id>/', views.blog_article),
    path('<int:article_id>/', views.note_article, name='note_article'),
]

JXProject/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

JXProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% block yangshi %}{% endblock %}
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

JXProject/templates/calen.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'/>
    <link href='../static/css/fullcalendar.css' rel='stylesheet'/>
    <link href='../static/css/fullcalendar.print.css' rel='stylesheet' media='print'/>
    <script src='../static/js/moment.min.js'></script>
    <script src='../static/js/jquery.min.js'></script>
    <script src='../static/js/fullcalendar.min.js'></script>
    <script>

        $(document).ready(function () {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                defaultDate: '2021-06-12',
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                events: [
                    {
                        title: 'All Day Event',
                        start: '2021-06-01'
                    },
                    {
                        title: 'Long Event',
                        start: '2021-06-07',
                        end: '2021-06-10'
                    },
                    {
                        id: 999,
                        title: 'Repeating Event',
                        start: '2021-06-09T16:00:00'
                    },
                    {
                        id: 999,
                        title: 'Repeating Event',
                        start: '2021-06-16T16:00:00'
                    },
                    {
                        title: 'Conference',
                        start: '2021-06-11',
                        end: '2021-06-13'
                    },
                    {
                        title: 'Meeting',
                        start: '2021-06-12T10:30:00',
                        end: '2021-06-12T12:30:00'
                    },
                    {
                        title: 'Lunch',
                        start: '2021-06-12T12:00:00'
                    },
                    {
                        title: 'Meeting',
                        start: '2021-06-12T14:30:00'
                    },
                    {
                        title: 'Happy Hour',
                        start: '2021-06-12T17:30:00'
                    },
                    {
                        title: 'Dinner',
                        start: '2021-06-12T20:00:00'
                    },
                    {
                        title: 'Birthday Party',
                        start: '2021-06-13T07:00:00'
                    },
                    {
                        title: 'Click for Google',
                        url: 'http://google.com/',
                        start: '2021-06-28'
                    }
                ]
            });

        });

    </script>
    <style>

        body {
            margin: 40px 10px;
            padding: 0;
            font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
            font-size: 14px;
        }

        #calendar {
            max-width: 900px;
            margin: 0 auto;
        }

    </style>
</head>
<body>

<div id='calendar'></div>

</body>
</html>

JXProject/templates/footer.html
<div class="container"> <hr>
    <p class="text-center">@山东大学</p>
</div>

JXProject/templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="https://www.sc.sdu.edu.cn/"> <!-- 导航栏头部 （折叠按钮+品牌标签）-->
                <img src="{% static '/images/sdlogo.png' %}" width="100px">
            </a>
        </div>
        <div> <!-- 导航栏目 -->
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">首页</a></li>
                <li><a href="{% url 'note:note_title' %}">通知</a></li>
                <li><a href="{% url 'course:course_list' %}">课程</a></li>
                <li><a href="{% url 'article:article_titles' %}">交流</a></li>
                <li><a href="{% url 'test' %}">实验</a></li>
                <li><a href="{% url 'course:about'%}">关于本站</a></li>
            </ul>



            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                    <li>
                        <div class="dropdown" style="margin-top:8px">
                            <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu'
                                    data-toggle='dropdown'>{{ user.username }}
                                <span class='caret'></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                                <li><a href="{% url 'article:article_column' %}">文章管理</a></li>
                                <li><a href="{% url 'course:course_list' %}">课程管理</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'account:user_logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">登录</a></li>
                    <li><a href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}
                <form class="form-inline" action="article/" method="GET">
                    <input class="form-control" type="search" name="keyword"
                           placeholder="搜索..." aria-label="Search" value="{{ keyword }}">
                    <button class="btn btn-outline-success" type="submit">搜索</button>
                </form>
                </li>
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

{#<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>#}

JXProject/templates/home.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}
{% block yangshi %}
    <meta charset='utf-8'/>
    <link href='../static/css/fullcalendar.css' rel='stylesheet'/>
    <link href='../static/css/fullcalendar.print.css' rel='stylesheet' media='print'/>

    <style>

        body {
            margin: 40px 10px;
            padding: 0;
            font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
            font-size: 14px;
        }

        #calendar {
            max-width: 900px;
            margin: 0 auto;
        }

    </style>
{% endblock %}
{% block content %}
{#<div class="container">#}
{#        <h1>Welcome!</h1>#}
{##}
{#        <div class="row">#}
{#            <div class='col-sm-6'>#}
{#                <div class="form-group">#}
{#                    <label>选择日期：</label>#}
{#                    <!--指定 date标记-->#}
{#                    <div class='input-group date' id='datetimepicker1'>#}
{#                        <input type='text' class="form-control"/>#}
{#                        <span class="input-group-addon">#}
{#                    <span class="glyphicon glyphicon-calendar"></span>#}
{#                </span>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <div class='col-sm-6'>#}
{#                <div class="form-group">#}
{#                    <label>选择日期+时间：</label>#}
{#                    <!--指定 date标记-->#}
{#                    <div class='input-group date' id='datetimepicker2'>#}
{#                        <input type='text' class="form-control"/>#}
{#                        <span class="input-group-addon">#}
{#                    <span class="glyphicon glyphicon-calendar"></span>#}
{#                </span>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{#        {% load static %}#}
{#        <img src="{% static 'images/rili1.png' %}">#}
{#    </div>#}
{##}
{##}
{#    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">#}
{#    <link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"#}
{#          rel="stylesheet">#}
{##}
{#    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>#}
{#    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>#}
{#    <script src="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>#}
{#    <script>$(function () {#}
{#        $('#datetimepicker1').datetimepicker({#}
{#            format: 'YYYY-MM-DD',#}
{#            locale: moment.locale('zh-cn')#}
{#        });#}
{#        $('#datetimepicker2').datetimepicker({#}
{#            format: 'YYYY-MM-DD hh:mm',#}
{#            locale: moment.locale('zh-cn')#}
{#        });#}
{#    });#}
{##}
{#    $(function () {#}
{#        var picker1 = $('#datetimepicker1').datetimepicker({#}
{#            format: 'YYYY-MM-DD',#}
{#            locale: moment.locale('zh-cn'),#}
{#            //minDate: '2016-7-1'#}
{#        });#}
{#        var picker2 = $('#datetimepicker2').datetimepicker({#}
{#            format: 'YYYY-MM-DD',#}
{#            locale: moment.locale('zh-cn')#}
{#        });#}
{#        //动态设置最小值#}
{#        picker1.on('dp.change', function (e) {#}
{#            picker2.data('DateTimePicker').minDate(e.date);#}
{#        });#}
{#        //动态设置最大值#}
{#        picker2.on('dp.change', function (e) {#}
{#            picker1.data('DateTimePicker').maxDate(e.date);#}
{#        });#}
{#    });#}
{##}
{#    $('#datetimepicker1').datetimepicker({#}
{#        format: 'YYYY-MM-DD',#}
{#        locale: moment.locale('zh-cn'),#}
{#        defaultDate: "2021-1-1"#}
{#    });#}
{#    </script>#}
    <div id='calendar'></div>
{% endblock %}
{% block javascript %}
    <script src='../static/js/moment.min.js'></script>
    <script src='../static/js/jquery.min.js'></script>
    <script src='../static/js/fullcalendar.min.js'></script>
    <script>

        $(document).ready(function () {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                defaultDate: '2021-06-12',
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                events: [
                    {
                        title: '六一',
                        start: '2021-06-01'
                    },
                    {
                        title: '高考',
                        start: '2021-06-07',
                        end: '2021-06-09'
                    },
                    {
                        title: '填写毕业生登记表',
                        start: '2021-06-07T15:00:00',
                        end: '2021-06-08'
                    },
                    {
                        id: 999,
                        title: '跑步',
                        start: '2021-06-10T18:00:00'
                    },
                    {
                        id: 999,
                        title: '跑步',
                        start: '2021-06-14T18:00:00'
                    },
                    {
                        id: 999,
                        title: '跑步',
                        start: '2021-06-17T18:00:00'
                    },
                    {
                        title: '端午节',
                        start: '2021-06-12',
                        end: '2021-06-14'
                    },
                    {
                        title: '六级',
                        start: '2021-06-12T14:00:00'
                    },
                    {
                        title: '看MOOC',
                        url: 'https://www.icourse163.org/',
                        start: '2021-06-28'
                    }
                ]
            });

        });

    </script>
{% endblock %}

JXProject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

JXProject/templates/paginator.html
<div class="pagination"> 
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }} 
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">下一页</a> {% endif %}
    </span>
</div>
    